version: "3.7"

services:
  postgres:
    image: postgres:11.5
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54320:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks: 
      - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - postgres

networks: 
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: